### ISSUE TITLE
after touching nipple whole website get Stuck on IOS Devices

### ISSUE THREAD

**Issue by worl44** [yoannmoinet/nipplejs#64]
Hello, 
greate Plugin but sadly only on IOS devices the whole website stuck after touching one nipple ( i use the static mode )  and must be reloaded. First i thought its only a Safari problem but the problem encounter also on Chrome (only on IOS devices ). 

I already try 

$(document).on('touchcancel', function(event) {
//do something()
});

like @adriancabouli mentioned in some other comments but it dosent help. 

I would be happy for some help.

**Comment by stonecompass** [comment]
Getting the same bug here :(

**Comment by yoannmoinet** [comment]
Is there any error in the console?

**Comment by stonecompass** [comment]
Not in my case at least.

**Comment by worl44** [comment]
in my case there is also no error or warning in the console. It seems to work correct.

**Comment by stonecompass** [comment]
@yoannmoinet  Any idea what it could be or a workaround maybe?

**Comment by yoannmoinet** [comment]
@stonecompass unfortunately, I have no iOS devices to test it on.

I'll see what I can do to reproduce the issue. For now, I'm affraid I don't know what could provoque this kind of freeze, especially if it's not throwing any error, and only happening on latest iOS version.

In the meantime if you could share your setup, it will help me once I get to test it on a virtual device.

**Comment by stonecompass** [comment]
I've tried using an iPhone 6 with iOS 11.2 and an iPad using 11.2.1.
The problem happens in Safari and Chrome on both devices.
Hope that helps a little.

**Comment by worl44** [comment]
Im also using an Ipad 11.2.1. I allready tried on iPadian iOS 10. There it works.

**Comment by yoannmoinet** [comment]
Thanks for the replies.

Did you test with the demo @stonecompass and @worl44 ?

**Comment by stonecompass** [comment]
Yes, it seems as if it only breaks if you use the 'static' setting!

**Comment by yoannmoinet** [comment]
all right, I'll have a look. Thanks for your help, both of you !

**Comment by worl44** [comment]
@stonecompass @yoannmoinet No, it breaks also in dynamic mode but there only the nipple stuck, but that mentioned allready in some other comments. Yes i try also the demo, there are the same problems.

**Comment by yoannmoinet** [comment]
Good news, I'm able to reproduce it in the simulator!

**Comment by stonecompass** [comment]
Awesome! :D

**Comment by yoannmoinet** [comment]
Hey, I've pushed a new version that should fix this... can you confirm?

**Comment by stonecompass** [comment]
It works! Thank you for the effort and quick solution!

**Comment by worl44** [comment]
@yoannmoinet sorry, but the bug still encounter in my case. Also i made a mistake i use a ipad with version 10.3.2

**Comment by yoannmoinet** [comment]
Can you give me more details please?
I'll try on a different version of iOS, if I can.
But is it the exact same bug?

**Comment by worl44** [comment]
@yoannmoinet  So i don't know what details i should give you, because there is no error or something special, so i try to describe my usecase and more detailed the error that occur.

I have a website with more than 1  nipple. There are 5 nipple on the page.  After i touch one of these nipples the website cant scroll anymore or do something else it stuck and must be reloaded, but the nipples still work, they don't stuck like in dynamic mode. There is nothing special in use what can cause this effect. I only use Html5, Bootstrap, CSS and your nipple.js.min. 

Yes this is the same bug as before and it only occur at IOS devices, as i described before.
I hope that helps you a bit. Have you more questions or you need more specific details, please let me know. 

Thank you very much for your effort.

**Comment by yoannmoinet** [comment]
@worl44 are you 100% you're using the latest version.

Can you reproduce the issue with the demo?

I'll need to have access to your setup/code if you want me to reproduce the bug.

**Comment by yoannmoinet** [comment]
@worl44 anything new?

**Comment by worl44** [comment]
sorry , the holidays! I try to build a test website to reproduce the bug and give you access to this page. I try to make it in the next few days.

**Comment by patrickheuel** [comment]
Hey, do you guys have any update on this? I'm facing the same issue in version 0.7.1.
After touching the nipple on an iOS device (11.4.1), nothing else is touchable until I refresh the page. Destroying the nipple "ontouchend" doesn't work for me either...

**Comment by lazerwalker** [comment]
@patrickheuel Yep, I'm still running into it as well. Starting to debug, but hopefully someone with more context will have good ideas.

**Comment by ldehaes** [comment]
I still have the same problem on iOS devices!
Are you still working on this?
I don't have enough experience to debug this myself ...

**Comment by lazerwalker** [comment]
@ldehaes Check out https://github.com/yoannmoinet/nipplejs/issues/72#issuecomment-416231566. I wasn't able to solve the problem, but someone else's quick fix did the job well enough for me to stop looking into it.

**Comment by ldehaes** [comment]
@lazerwalker adding the quick fix did not do the job for me, it is also a different issue than the one described here.

**Comment by patrickheuel** [comment]
@lazerwalker @yoannmoinet quick fix didn't help for me neither... Any other ideas?

**Comment by paladin-t** [comment]
The same issue was driving me mad, until using the `dynamic` mode. And here's my workaround to simulate `static` by assigning the position explicitly

```
Collection.prototype.processOnStart = function (evt) {
    var self = this;
    var opts = self.options;
    var indexInIdles;
    var identifier = self.manager.getIdentifier(evt);
    var pressure = evt.force || evt.pressure || evt.webkitForce || 0;
    //var position = {
        //x: evt.pageX,
        //y: evt.pageY
    //};
    var position = opts.position;
    ...
}

...

// Config the `fadeTime` to `0` as well.
```

Really hope someone can explain the behaviour.

**Comment by jbshin-gemiso** [comment]
> The same issue was driving me mad, until using the `dynamic` mode. And here's my workaround to simulate `static` by assigning the position explicitly
> 
> ```
> Collection.prototype.processOnStart = function (evt) {
>     var self = this;
>     var opts = self.options;
>     var indexInIdles;
>     var identifier = self.manager.getIdentifier(evt);
>     var pressure = evt.force || evt.pressure || evt.webkitForce || 0;
>     //var position = {
>         //x: evt.pageX,
>         //y: evt.pageY
>     //};
>     var position = opts.position;
>     ...
> }
> 
> ...
> 
> // Config the `fadeTime` to `0` as well.
> ```
> 
> Really hope someone can explain the behaviour.


I worked well in dynamic mode, but in static mode, the joystick did not respond or the app crashed.

But it was solved this way. thank you !!
I hope others will try it when they encounter problems in static mode.
