### ISSUE TITLE
joystick in 'dynamic' mode gets stuck on iOS

### ISSUE THREAD

**Issue by otoinsa** [yoannmoinet/nipplejs#94]
Steps to replicate:

1. Create iOS app with WKWebView running nipple js in the webview side of things
2. Init nipple js in runtime with mode: 'dynamic'
3. Tap 3 times fairly quickly on the nipple area you've set up and joystick will get stuck

I've noticed that this won't happen in 'semi' mode.
Yes, I have looked at the previous threads and setting fadeTime to 0 does not help.
Also no errors in js console...

using:
iOS 12
nipplejs 0.8.0

![nipplebug](https://user-images.githubusercontent.com/7381482/50647482-569f7780-0f81-11e9-8494-f3ad9067c9c3.gif)

On Android WebView works perfectly for my case,
really like this library :)

Could it be that the new joystick/s get created while the old one is still around?

Not exactly sure how is Safari different in terms of touch events in js.

**Comment by rkdrnf** [comment]
Not exactly this but similar thing also happens in the example page. 
if you click quickly with dynamic mode, joystick image does not disappear anymore.
I checked that "start" event is called but no "end" event called when this happens.
tested with iPhone X

**Comment by yoannmoinet** [comment]
Thank you for reporting this, I'll have a look.

**Comment by iodev** [comment]
fixed in commit cf126f2e164b6244a9474be6d448bd11da19acea

**Comment by Steckdoserich** [comment]
Does your fix also fixes my problem #93?

**Comment by otoinsa** [comment]
The issue still persists for me, all of my iOS testers report the same thing, so I’ll be moving away from nipple.js, atleast for iOS.

I understand the creator of nipple.js does not have a iOS test device, the issue is hard to replicate on Simulator, but in a fast paced game on a real device it takes under a minute to crash on iOS 12.

I’m not sure where to start looking, probably somewhere around the place where the finger gets lifted, but for now I’ll just stick with another library on iOS

**Comment by Steckdoserich** [comment]
Which library are you going to use instead?
